### ISSUE TITLE
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by Den-dp** [tarsinzer/routerkit#238]
### Description of the problem

An unhandled exception while running `ng add @routerkit/core` in fresh `@angular/cli@13.3.7` project.

### Steps To Reproduce

```
npm i @angular/cli@13.3.7 -g
ng new ngcli1337 --minimal --routing true --inline-style --inline-template --skip-tests --style=css
cd ngcli1337
ng add @routerkit/core
```

### Expected behavior

Should install library without error.

### Screenshots

![image](https://user-images.githubusercontent.com/1770529/171620943-d1f4d269-53eb-4033-a1a6-f0e8fe800c6d.png)

angular-errors.log:
```
[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (C:\Users\bendrikov\fun\ngcli1337\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (C:\Users\bendrikov\fun\ngcli1337\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at C:\Users\bendrikov\fun\ngcli1337\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (C:\Users\bendrikov\fun\ngcli1337\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\bendrikov\fun\ngcli1337\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (C:\Users\bendrikov\fun\ngcli1337\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (C:\Users\bendrikov\fun\ngcli1337\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at C:\Users\bendrikov\fun\ngcli1337\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (C:\Users\bendrikov\fun\ngcli1337\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\bendrikov\fun\ngcli1337\node_modules\ajv\dist\compile\codegen\index.js:568:18)

```

### Versions:

- OS: Windows 10
- Angular: 13.3.7
- RouterKit: 0.9.3

**Comment by tarsinzer** [comment]
@Den-dp hey! Thanks for pointing out that issue!

Currently, we don't support angular v13, but I think we can bump our support versions up to 14 (oh, 14th was released 3 hours ago)

**Comment by Den-dp** [comment]
Both news sounds great to me 😏

**Comment by tarsinzer** [comment]
@Den-dp sorry for being late. I have good news. 

The latest release 0.10.0 now should support both Angular v13 and Angular v14.

**Comment by Den-dp** [comment]
@tarsinzer works with v14 👍 

Thanks for your work and no worries. I appreciate your efforts given the hard times we live in
